version: 2.1
jobs:
  build:
    working_directory: ~/guilloutran.com
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo yarn self-update'
      - run:
          name: install-dependent
          command: yarn add gatsby-cli && yarn add codecov
      - run:
          name: build
          command: yarn build
      - run:
          name: code-coverage
          command: 'yarn codecov'
